param([string]$Fxc)
$ErrorActionPreference = 'Stop'

# Development-only generator. Release builds embed DXBC and do not link the
# HLSL compiler. /Qstrip_reflect and /Qstrip_debug keep the fixed shaders small.
if (-not $Fxc) {
    $Fxc = Join-Path ${env:ProgramFiles(x86)} 'Windows Kits\10\bin\10.0.26100.0\x64\fxc.exe'
}
if (-not (Test-Path -LiteralPath $Fxc -PathType Leaf)) {
    throw 'fxc.exe is required; pass -Fxc with a Windows SDK compiler path.'
}
$source = Join-Path $PSScriptRoot 'terminal.hlsl'
$header = Join-Path $PSScriptRoot 'terminal_bytecode.h'
$entries = @('bg_vs', 'text_vs', 'bg_ps', 'cellbg_ps', 'text_ps')
$temporary = Join-Path $PSScriptRoot ('.shader-build-' + [guid]::NewGuid().ToString('N'))
[void](New-Item -ItemType Directory -Path $temporary)
try {
    $output = [System.Text.StringBuilder]::new()
    [void]$output.AppendLine('/* Generated by generate-shaders.ps1 with Windows SDK fxc 10.0.26100.0. */')
    [void]$output.AppendLine('/* terminal.hlsl SHA256: ' + (Get-FileHash -LiteralPath $source -Algorithm SHA256).Hash.ToLowerInvariant() + ' */')
    [void]$output.AppendLine('#ifndef NOCTTY_D3D11_TERMINAL_BYTECODE_H')
    [void]$output.AppendLine('#define NOCTTY_D3D11_TERMINAL_BYTECODE_H')
    foreach ($entry in $entries) {
        $shaderProfile = if ($entry.EndsWith('_vs')) { 'vs_5_0' } else { 'ps_5_0' }
        $compiled = Join-Path $temporary ($entry + '.dxbc')
        & $Fxc /nologo /T $shaderProfile /E $entry /O3 /Ges /Qstrip_reflect /Qstrip_debug /Fo $compiled $source
        if ($LASTEXITCODE -ne 0) { throw ('Shader compilation failed: ' + $entry) }
        $bytes = [System.IO.File]::ReadAllBytes($compiled)
        [void]$output.AppendLine('static const unsigned char noctty_' + $entry + '[] = {')
        for ($offset = 0; $offset -lt $bytes.Length; $offset += 16) {
            $last = [Math]::Min($offset + 15, $bytes.Length - 1)
            $values = @($bytes[$offset..$last] | ForEach-Object { '0x{0:x2}' -f $_ })
            [void]$output.AppendLine('    ' + ($values -join ', ') + ',')
        }
        [void]$output.AppendLine('};')
        Write-Output ($entry + ': ' + $bytes.Length + ' bytes')
    }
    [void]$output.AppendLine('#endif')
    [System.IO.File]::WriteAllText($header, $output.ToString().Replace("`r`n", "`n"), [System.Text.UTF8Encoding]::new($false))
} finally {
    # Delete only the exact files in the newly created generator directory.
    Get-ChildItem -LiteralPath $temporary -File | Remove-Item -Force
    Remove-Item -LiteralPath $temporary
}
