#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

# check URL EXPECT_CODE [EXPECT_LOCATION_SUBSTR] — curl a URL and report.
check() {
  local url="$1" want="$2" want_loc="${3:-}" code loc
  code=$(curl -s -o /dev/null -w '%{http_code}' --max-time 15 "$url" || echo 000)
  if [[ "$code" == "$want" ]]; then
    if [[ -n "$want_loc" ]]; then
      loc=$(curl -s -o /dev/null -w '%{redirect_url}' --max-time 15 "$url" || true)
      if [[ "$loc" == *"$want_loc"* ]]; then
        printf '  %s✓%s %s → %s (→ %s)\n' "$GREEN" "$RESET" "$url" "$code" "$loc"; return 0
      fi
      warn "$url returned $code but redirects to '$loc' (wanted *$want_loc*)"; return 1
    fi
    printf '  %s✓%s %s → %s\n' "$GREEN" "$RESET" "$url" "$code"; return 0
  fi
  warn "$url returned $code (wanted $want) — may need DNS propagation; re-run later"
  return 1
}

banner "Noctty cutover — Cloudflare domains + CI runner"

# ── Stage 1: attach noctty.com to the new Pages project ───────────────────
stage "Attach noctty.com to the 'noctty' Pages project"
say "The 'noctty' Pages project already exists and serves https://noctty.pages.dev."
say "Now point your apex domain at it (Cloudflare auto-creates the DNS record)."
open_url "https://dash.cloudflare.com/?to=/:account/pages/view/noctty/domains"
step "Click 'Set up a custom domain' (or 'Add a custom domain')."
step "Enter: noctty.com  — then Continue and Activate domain."
note "Only the apex here. www is handled as a redirect in the next stage."
pause "Done? Press Enter to verify."
check "https://noctty.com/" 200 || true

# ── Stage 2: www.noctty.com → noctty.com 301 ──────────────────────────────
stage "Redirect www.noctty.com to the apex (301)"
say "The deploy pipeline verifies a zone-level 301 from www to the apex."
open_url "https://dash.cloudflare.com/?to=/:account/:zone/dns/records&zone=noctty.com"
step "In the noctty.com zone DNS: add record  Type AAAA, Name www,"
step "  IPv6 address 100:: , Proxy status ON (orange cloud). Save."
note "100:: is a discard placeholder; the proxy just needs a record to fire rules."
step "Now open Rules for the zone:"
open_url "https://dash.cloudflare.com/?to=/:account/:zone/rules/redirect-rules&zone=noctty.com"
step "Create rule (template 'Redirect from WWW to Root' works), or custom:"
step "  When: Hostname equals www.noctty.com"
step "  Then: Dynamic redirect, 301, expression:"
step "    concat(\"https://noctty.com\", http.request.uri.path)"
step "  Preserve query string: ON. Deploy."
pause "Done? Press Enter to verify."
check "https://www.noctty.com/getting-started" 301 "noctty.com" || true

# ── Stage 3: winghostty.com → noctty.com 301 ──────────────────────────────
stage "Redirect winghostty.com (legacy) to noctty.com"
say "winghostty.com is still attached to the old 'winghostty' Pages project."
say "Detach it there first, then redirect the whole zone to noctty.com."
open_url "https://dash.cloudflare.com/?to=/:account/pages/view/winghostty/domains"
step "Remove custom domains winghostty.com and www.winghostty.com from the"
step "  old 'winghostty' Pages project (keep the project itself for now)."
step "In the winghostty.com zone DNS: make sure apex and www each have a"
step "  proxied record (add  AAAA @ 100::  and  AAAA www 100::  if removal"
step "  left them empty)."
open_url "https://dash.cloudflare.com/?to=/:account/:zone/rules/redirect-rules&zone=winghostty.com"
step "Create redirect rule:"
step "  When: Hostname is in { winghostty.com  www.winghostty.com }"
step "  Then: Dynamic redirect, 301, expression:"
step "    concat(\"https://noctty.com\", http.request.uri.path)"
step "  Preserve query string: ON. Deploy."
pause "Done? Press Enter to verify."
check "https://winghostty.com/" 301 "noctty.com" || true
check "https://www.winghostty.com/" 301 "noctty.com" || true

# ── Stage 4: winghostty.dev (only if you still own it) ────────────────────
stage "winghostty.dev — redirect only if the zone still exists"
say "winghostty.dev currently returns NXDOMAIN publicly — it may have lapsed"
say "or was never in this Cloudflare account."
open_url "https://dash.cloudflare.com/?to=/:account/home"
step "Check the Websites list for winghostty.dev."
if confirm "Is winghostty.dev listed in your account?"; then
  step "Repeat the Stage 3 pattern for that zone: proxied apex+www records,"
  step "  then a 301 dynamic redirect to concat(\"https://noctty.com\", http.request.uri.path)."
  pause "Done? Press Enter to verify."
  check "https://winghostty.dev/" 301 "noctty.com" || true
else
  note "Skipping — nothing to redirect. (If it lapsed, no action needed.)"
fi

# ── Stage 5: re-register the self-hosted CI runner ────────────────────────
stage "Re-register the self-hosted runner as 'noctty-interactive'"
say "The repo currently has ZERO registered runners (the rename orphaned it),"
say "and CI's interactive job targets label: noctty-interactive."
say ""
say "Generating a fresh registration token (valid ~1 hour)…"
if RUNNER_TOKEN=$(gh api -X POST repos/amanthanvi/noctty/actions/runners/registration-token --jq .token 2>/dev/null); then
  printf '  %sRegistration token:%s %s\n' "$BOLD" "$RESET" "$RUNNER_TOKEN"
  say ""
  step "On the runner host machine, in the runner install directory, run:"
  step "  .\\config.cmd remove --local        (clears the stale winghostty registration)"
  step "  .\\config.cmd --url https://github.com/amanthanvi/noctty \\"
  step "     --token $RUNNER_TOKEN \\"
  step "     --labels noctty-interactive --unattended"
  step "  then restart it (.\\run.cmd, or reinstall the service via svc scripts)."
else
  warn "Could not mint a registration token via gh; get one from the URL below."
  open_url "https://github.com/amanthanvi/noctty/settings/actions/runners/new"
fi
pause "Runner reconfigured? Press Enter to verify."
if gh api repos/amanthanvi/noctty/actions/runners --jq '[.runners[].labels[].name] | join(",")' 2>/dev/null | grep -q noctty-interactive; then
  printf '  %s✓%s runner with label noctty-interactive is registered\n' "$GREEN" "$RESET"
else
  warn "no runner with label noctty-interactive visible yet — CI interactive jobs will queue until it appears"
  SKIPPED+=("runner re-registration (label noctty-interactive)")
fi

# ── Stage 6: retire the old 'winghostty' Pages project (optional) ─────────
stage "Retire the old 'winghostty' Pages project (optional, destructive)"
say "Once the redirects above have been verified working for a few days, the"
say "old direct-upload Pages project serves nothing and can be deleted."
warn "Deletion is irreversible. Recommended: skip today, re-run this wizard later."
if confirm "Delete the 'winghostty' Pages project NOW?"; then
  if confirm "Really delete? Its domains must already be detached (Stage 3)."; then
    wrangler pages project delete winghostty --yes && \
      printf '  %s✓%s old Pages project deleted\n' "$GREEN" "$RESET" || \
      warn "delete failed — do it in the dashboard when ready"
  else
    note "Skipped."
    SKIPPED+=("delete old 'winghostty' Pages project (when redirects are proven)")
  fi
else
  note "Skipped — sensible. Re-run this script later; earlier stages re-verify quickly."
  SKIPPED+=("delete old 'winghostty' Pages project (when redirects are proven)")
fi

finish
